project:
  type: website
  output-dir: docs

website:
  title: "ESM 254 Spring 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



