---
title: "ESM 254: Quantitative Fisheries Science Edition"
subtitle: "Draft Syllabus"
---

# Disclaimer
The details outlined below are subject to revision and refinement as the instructor continues to develop the course for Spring 2023.

# Course Description
Fisheries science and the quantitative methods developed for producing scientific advice for management are excellent case studies for students seeking to work at the forefront of solving critical environmental problems. My intent for this course is to demonstrate that quantitative marine ecology can transcend traditional and siloed academic exercises to be used to serve the communities that rely on living marine resources.

# Course Learning Goals
Throughout this course, students will

- Describe how settler-colonialism and white supremacy shape who gets to participate in fisheries and marine conservation through assigned course readings and in-class discussions [Knowledge]* 
- Summarize key  ecological concepts that drive marine population dynamics and influence the implementation of quantitative methods [Comprehension]*
- Compare and contrast the quantitative methods used for developing scientific advice [Comprehension]*
- Implement a subset of quantitative methods for producing scientific advice [Application]*
- Design a list of key questions to ask when evaluating scientific advice [Synthesis]*
- Interpret key outputs presented as scientific advice [Synthesis]*

*Check out the [Teaching Jargon](#teaching-jargon) section for more information.

# Example Course Topics
Many of these topics will span multiple lectures.

- Introduction to Quantitative Marine Ecology & Fisheries Science
- Overview of Knowledge Systems and Western Science
- Marine Ecology and Population Dynamics
- Introduction to Modeling
- The 5 Steps of Fisheries Management (A simplified framework)
    - Step 1. Data Collection 
    - Step 2. Assessing Stock Status
    - Step 3. Setting Catch Limits
    - Step 4. Making regulations
    - Step 5. Research and Data Needs
- Overview of Management Strategy Evaluation

# Course Structure
The course structure is subject to adjustment before the first meeting of Spring Quarter.

## Lectures & in-class exercises
There are two 1 hour and 15-minute class meetings per week. Lectures are pre-recorded and made available on the course website before class. Students are expected to watch the lectures before class to prepare for the hands-on in-class discussions and exercises.

## Assignments
There are five graded assignment types:

- ~20 Lecture Quizzes (Online, Formative)
- ~20 Entry slips/Exit slips (In-person, Formative)
- ~10 Weekly short-form writing reflection assignments (Online, Formative)
- ~2 Take home exams (Online, Summative)
- Final project written report and presentation (Online and In-person, Summative)

## Grading
| Assignment Type | Weight |
| --------------- | ------ |
| Quizzes         | 20%    |
| Entry / exit slips | 5%  |
| Weekly written reflections | 10% |
| Take home exams | 30% |
| Final project | 35% |

# Teaching Jargon
- The words in [brackets] in the Course Goals section are from [Bloom's Taxonomy](https://en.wikipedia.org/wiki/Bloom%27s_taxonomy), a hierarchical modeling framework for designing learning objectives.
- Formative assessments/assignments: help students learn and practice the course content and are low-stakes (i.e., have low weights in your grading scheme)
- Summative assessments/assignments: help me assess how students are performing on the learning objectives for each unit and are typically higher-stakes (i.e., higher weighting in the gradebook)

